---
title: Silly eyes
hero_image: images/banner.png
description: Create your own app with a character whose eyes follow the mouse pointer
version: 4
listed: true
copyedit: false
last_tested: "2021-02-25"
steps:
  - 
    title: Introduction
  - 
    title: Your character
  - 
    title: Make silly eyes
    completion: engaged
  - 
    title: Sprite effects
  - 
    title: Stage effects
    completion: internal
  - 
    title: Reflection
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Upgrade your project
  - 
    title: Share
  - 
    title: What next?
