---
title: Ojos tontos
hero_image: images/banner.png
description: Crea tu propia aplicación con un personaje cuyos ojos siguen el puntero del ratón
version: 4
listed: true
copyedit: false
last_tested: '2021-02-25'
steps:
  - 
    title: You will make
  - 
    title: Create your character
  - 
    title: Crea ojos tontos
    completion:
      - engaged
  - 
    title: Add sprite effects
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
  - 
    title: Share
  - 
    title: What next?
