---
title: Des yeux stupides
hero_image: images/banner.png
description: Créer ta propre application avec un personnage dont les yeux suivent le pointeur de la souris
version: 4
listed: true
copyedit: false
last_tested: '2021-02-25'
steps:
  - 
    title: You will make
  - 
    title: Create your character
  - 
    title: Créer des yeux stupides
    completion:
      - engaged
  - 
    title: Add sprite effects
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
  - 
    title: Share and play
  - 
    title: What next?
